sudo: required
language: cpp

git:
    depth: 3


matrix:
    fast_finish: true
    include:
        - os: linux
          env: TARGET=web
        - os: linux
          compiler: gcc
          env: TARGET=desktop
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
                  packages:
                      - python-dev
                      - g++-7
                      - qt510-meta-minimal
                      - qt510script
        - os: osx
          osx_image: xcode10
        - os: windows
    allow_failures:
        - os: windows

install:
    - . $TRAVIS_BUILD_DIR/dist/ci-wrap.sh install $TRAVIS_OS_NAME $TARGET
script:
    - . $TRAVIS_BUILD_DIR/dist/ci-wrap.sh script $TRAVIS_OS_NAME $TARGET
after_success:
    - . $TRAVIS_BUILD_DIR/dist/ci-wrap.sh after_success $TRAVIS_OS_NAME $TARGET
before_deploy:
    - . $TRAVIS_BUILD_DIR/dist/ci-wrap.sh before_deploy $TRAVIS_OS_NAME $TARGET

deploy:
    - provider: pages
      skip_cleanup: true
      github_token: $GH_TOKEN
      local_dir: $TRAVIS_BUILD_DIR/gh-pages
      on:
          branch: master
          condition: $TARGET = web
    - provider: releases
      skip_cleanup: true
      api_key:
          secure: KBiyKkeDNQQE7m1WI0s9+YRTiO9eAAYZTljTrTMWicKWRo28NNNGaeZ5DYZ0J0CCnJAaywIPBHsfcis10rLyIB+GYyVN6oToI/OZf/aufLry4zbmiB/LQva4zln6zQAj/SIxUVRzu6rG30s+imAxUzbIboAHD068yTKpd3A/IMDCutI1OZZ4TPFb4fUZauDvGn3j30fty13OyRs3aEyCd7ldHxydnMPJsOZfp26KTPokWItUnXrfhv7igjRPRHu3DAoxhZBO3gWbPrT0QAUP59bD4A97PXpXVyqiE7A6vK4jvbYCuYsbEyCj2HT4QZ2OLGt9MEo4+/4C0almNd9FUYwXKK9jZmfqSQfc1EWmBJCQ+ABtIIxExbXs6V6tsfYxcAxU1NC8jaMFwIe4sX67eKP5IUE2/wmlqxGIaTH3Lm3S7HzyNHMlrLPdEh4csoo+V2ljmIDCav02huKv5DixLUfN5olESb0xgyU8iOiEOrA2P2uCDfKsdbOkwJHvHKgZx/Y93ysa5Z1X5NKgAoMzYBXWVihOwa93MRxWyTWxFZKzolhFzCBH2+VWCwhLKJ9+rpLC5z1zipidzHC3/yWtFK6BZ2GSlDW20uQGWMWc88Wyp+JFVYqXHG4RF7veM2+s2vxlNzHqBACK7S6CNk2ffbbAJC9amdzKIKrBDAvw0ko=
      file: $DEPLOY_FILE
      draft: true
      on:
          tags: true
          condition: $TARGET != web && $TRAVIS_OS_NAME != windows
